version: 2

updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    commit-message:
      prefix: 'build'
      prefix-development: 'chore'
      include: scope
    labels:
      - 🧩 dependencies
      - 🤖 bot
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    commit-message:
      prefix: 'ci'
      include: scope
    labels:
      - 🧩 dependencies
      - 🤖 bot
